### ISSUE TITLE
Uncaught TypeError: $.cf.isValid is not a function

### ISSUE THREAD

**Issue by firstcloudconsulting** [nehakadam/DateTimePicker#140]
No matter how I load this, what order, etc. I get the same error:

> calenstyle.js:764 Uncaught TypeError: $.cf.isValid is not a function
>     at new CalenStyle (calenstyle.js:764)
>     at HTMLDivElement.<anonymous> (calenstyle.js:727)
>     at Function.each (jquery-1.11.1.min.js:2)
>     at m.fn.init.each (jquery-1.11.1.min.js:2)
>     at m.fn.init.$.fn.CalenStyle (calenstyle.js:721)
>     at HTMLDocument.<anonymous> (calendar.js:4)
>     at j (jquery-1.11.1.min.js:2)
>     at Object.fireWith [as resolveWith] (jquery-1.11.1.min.js:2)
>     at Function.ready (jquery-1.11.1.min.js:2)
>     at HTMLDocument.J (jquery-1.11.1.min.js:2)

I even tried loading your CalenStyle example and get the same error, ref: [http://calenstyle.firstcloudconsulting.com/demo/CalExampleAddEventOnViewClick.htm](http://calenstyle.firstcloudconsulting.com/demo/CalExampleAddEventOnViewClick.htm)

**Comment by firstcloudconsulting** [comment]
Browser is Google Chrome Version 62.0.3202.94 (Official Build) (64-bit) in Mac OS High Sierra 10.13.1

**Comment by arius28** [comment]
I recently found CalenStyle by nehakadam and stumbled on the same error. It has been a year since the original issue was opened and the original poster might have solved or moved on but I thought I 'd share more info about the issue for anyone else who might stumble on it. 

The problem is not DateTimePicker on its own. It works fine on its own but when you use it together with CalenStyle calendar that's when the error occurs. This happens because there is a $.cf object that contains several functions and is created on the global scope from **both** plugins with different methods in each case. So DateTimePicker overrides the one created in calenstyle and then of course an error naturally occurs.

The easy way (mind you not the best way) to get it working in this case is to add an IF condition before the $.cf object is created in DateTimePicker to check if it already exists. If it does then don't create it again but instead append the functions to the already existing one. This should probably be changed more appropriately by nehakadam so that both plugins can interoperate correctly.

**Comment by firstcloudconsulting** [comment]
The previous fix worked, but _does not work_ with 0.1.39.

**Comment by arius28** [comment]
From what I see, the change made in version 0.1.39 shouldn't affect this fix. I just copied (in my local version) the change that was made in 0.1.39 and I don't seem to have an issue. 

For reference, what I do is replace the $.cf definition which currently is here: 
https://github.com/nehakadam/DateTimePicker/blob/c0a30c3e81876352da9819c29f7106f909dba7b2/dist/DateTimePicker.js#L160-L182

with the following:

```javascript
if (typeof $.cf == 'undefined') {
	$.cf = {
		_isValid: function (sValue) {
			return (sValue !== undefined && sValue !== null && sValue !== "");
		},
		_compare: function (sString1, sString2) {
			var bString1 = (sString1 !== undefined && sString1 !== null),
			bString2 = (sString2 !== undefined && sString2 !== null);
			if (bString1 && bString2) {
				if (sString1.toLowerCase() === sString2.toLowerCase())
					return true;
				else
					return false;
			} else
				return false;
		}
	};
} else {
	$.cf._isValid = function (sValue) {
		return (sValue !== undefined && sValue !== null && sValue !== "");
	};
	$.cf._compare = function (sString1, sString2) {
		var bString1 = (sString1 !== undefined && sString1 !== null),
		bString2 = (sString2 !== undefined && sString2 !== null);
		if (bString1 && bString2) {
			if (sString1.toLowerCase() === sString2.toLowerCase())
				return true;
			else
				return false;
		} else
			return false;
	};
}
```
Hope this helps

**Comment by firstcloudconsulting** [comment]
Thank you! I ended up doing something very similar based upon your previous comment, and that fixed the problem.

**Comment by reynierpsalas** [comment]
> Thank you! I ended up doing something very similar based upon your previous comment, and that fixed the problem.

Hi! I am having the same issue you reported. Could you please post the fix you finally found? Thanks!

**Comment by firstcloudconsulting** [comment]
It's been a while, but I had to add them outside of the primary class as so:
```
cf_isValid = function(sValue)
{
    return (sValue !== undefined && sValue !== null && sValue !== "");
};

cf_compare = function(sString1, sString2)
{
    var bString1 = (sString1 !== undefined && sString1 !== null),
    bString2 = (sString2 !== undefined && sString2 !== null);
    if(bString1 && bString2)
    {
        if(sString1.toLowerCase() === sString2.toLowerCase())
            return true;
        else
            return false;
    }
    else
        return false;
};
```

They're then just called directly, e.g.:
```
if(cf_isValid(oInputField))
```

Attached is a copy of that file if you want to do a diff and compare the differences.
[DateTimePicker.js.txt](https://github.com/nehakadam/DateTimePicker/files/5029815/DateTimePicker.js.txt)

**Comment by reynierpsalas** [comment]
> It's been a while, but I had to add them outside of the primary class as so:
> 
> ```
> cf_isValid = function(sValue)
> {
>     return (sValue !== undefined && sValue !== null && sValue !== "");
> };
> 
> cf_compare = function(sString1, sString2)
> {
>     var bString1 = (sString1 !== undefined && sString1 !== null),
>     bString2 = (sString2 !== undefined && sString2 !== null);
>     if(bString1 && bString2)
>     {
>         if(sString1.toLowerCase() === sString2.toLowerCase())
>             return true;
>         else
>             return false;
>     }
>     else
>         return false;
> };
> ```
> 
> They're then just called directly, e.g.:
> 
> ```
> if(cf_isValid(oInputField))
> ```
> 
> Attached is a copy of that file if you want to do a diff and compare the differences.
> [DateTimePicker.js.txt](https://github.com/nehakadam/DateTimePicker/files/5029815/DateTimePicker.js.txt)

Thanks for your help! I really appreciate it. I finally get it to work, staying on the last version of the package and using the script _build/jquery.datetimepicker.full.js_ (found this solution in another page on the internet).
